apiVersion: apps/v1
kind: Deployment
metadata:
  name: softgicapi
  namespace: desarrollo-sg
  labels:
    app: softgicapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: softgicapi
  template:
    metadata:
      labels:
        app: softgicapi
        version: "v1"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: softgicapi
          image: nx0x/softgicapi:latest
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "20Mi"
              cpu: "100m"
            limits:
              memory: "80Mi"
              cpu: "120m"
          env:
          - name: ENV
            value: "desarrollo-sg"
      nodeSelector:
        kubernetes.io/hostname: votan.interopera.jep.gov.co
---
apiVersion: v1
kind: Service
metadata:
  name: softgicapi-service
  namespace: desarrollo-sg
spec:
  selector:
    app: softgicapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
